/**
 * Curated list of uncommon English words.
 * These are words outside the top ~5,000 most frequently used,
 * but still findable in the Free Dictionary API.
 */
window.UNCOMMON_WORDS = [
  "abscond", "abstemious", "acerbic", "acrimony", "acumen",
  "admonish", "adroit", "aegis", "affable", "aggrandize",
  "alacrity", "alchemy", "algorithms", "allegory", "allusion",
  "altruism", "amalgam", "ambivalence", "ameliorate", "amiable",
  "amorphous", "anachronism", "anathema", "ancillary", "anecdote",
  "anomaly", "antediluvian", "antipathy", "apathy", "apocryphal",
  "approbation", "apropos", "arbitrary", "arcane", "archaic",
  "arduous", "articulate", "ascetic", "aspersion", "assiduous",
  "astringent", "atavism", "audacious", "auspicious", "austere",
  "avarice", "avuncular", "axiom",
  "baleful", "banal", "bane", "baroque", "bastion",
  "beatific", "bedlam", "behemoth", "bellicose", "belligerent",
  "bemused", "benediction", "benevolent", "berate", "bereft",
  "besmirch", "bilious", "blandishment", "blithe", "bombastic",
  "boorish", "bourgeois", "brazen", "brevity", "broach",
  "bucolic", "bumptious", "byzantine",
  "cabal", "cacophony", "cadence", "cajole", "callous",
  "calumny", "candor", "capitulate", "capricious", "cardinal",
  "carouse", "castigate", "catalyst", "caustic", "caveat",
  "censorious", "cerebral", "chagrin", "charlatan", "chimera",
  "circumlocution", "circumscribe", "circumspect", "clandestine", "clemency",
  "coalesce", "cogent", "cognizant", "colloquial", "commensurate",
  "compendium", "complaisant", "complicit", "compunction", "conciliatory",
  "conflagration", "congenial", "conjecture", "connive", "consternation",
  "contrite", "contumacious", "conundrum", "convivial", "copious",
  "corollary", "corporeal", "corroborate", "cosmopolitan", "countenance",
  "credulous", "crescendo", "culminate", "culpable", "cupidity",
  "curmudgeon", "cursory", "cynosure",
  "dalliance", "dearth", "debacle", "debilitate", "decadent",
  "decorum", "defamation", "deference", "deft", "defunct",
  "deleterious", "delineate", "deluge", "demagogue", "demeanor",
  "demure", "denigrate", "denouement", "depravity", "deprecate",
  "derelict", "deride", "derivative", "desiccate", "despondent",
  "despot", "desultory", "dexterous", "diaphanous", "diatribe",
  "dichotomy", "didactic", "diffident", "digress", "dilatory",
  "dilettante", "diminutive", "dirge", "disaffected", "discern",
  "discordant", "discreet", "disparage", "disparate", "dispassionate",
  "dissemble", "disseminate", "dissonance", "distill", "doctrinaire",
  "dogmatic", "doleful", "dormant", "dour", "draconian",
  "dubious", "dulcet", "duplicity",
  "ebullient", "eclectic", "edify", "efface", "effervescent",
  "efficacious", "effrontery", "effulgent", "egalitarian", "egregious",
  "elegy", "elicit", "elocution", "elucidate", "elusive",
  "emaciated", "emanate", "embellish", "embroil", "emissary",
  "empathy", "empirical", "emulate", "encomium", "endemic",
  "enervate", "engender", "enigma", "ennui", "ephemeral",
  "epitome", "equanimity", "equivocal", "erudite", "eschew",
  "esoteric", "espouse", "ethereal", "eulogy", "euphemism",
  "evanescent", "exacerbate", "exalt", "exasperate", "exemplary",
  "exhort", "exigent", "exonerate", "expatriate", "expedient",
  "expiate", "explicate", "exponent", "expunge", "extemporaneous",
  "extol", "extraneous", "extricate", "exuberant",
  "fabricate", "facetious", "fallacious", "fastidious", "fatuous",
  "fawn", "feckless", "felicitous", "fervent", "fester",
  "fiasco", "fickle", "filibuster", "flagrant", "florid",
  "foible", "foment", "forbearance", "forestall", "formidable",
  "fortuitous", "fractious", "frenetic", "frivolous", "frugal",
  "fulminate", "fulsome", "furtive", "futile",
  "gainsay", "galvanize", "gambit", "garish", "garrulous",
  "gauche", "germane", "glib", "gluttony", "gossamer",
  "grandiloquent", "gratuitous", "gregarious", "grouse", "guileless",
  "gustatory",
  "hackneyed", "halcyon", "hapless", "harbinger", "harangue",
  "hedonism", "hegemony", "heinous", "heresy", "hermetic",
  "heterogeneous", "heuristic", "hiatus", "hierarchy", "homogeneous",
  "hubris", "hyperbole", "hypothetical",
  "iconoclast", "idiosyncrasy", "ignominious", "illicit", "immutable",
  "impasse", "impassive", "impecunious", "impede", "imperious",
  "impertinent", "impervious", "impetuous", "implacable", "implicit",
  "importune", "impregnable", "impromptu", "impudent", "impugn",
  "impunity", "inadvertent", "incandescent", "inchoate", "incipient",
  "incisive", "incongruous", "incorrigible", "inculcate", "incumbent",
  "indecorous", "indefatigable", "indelible", "indifferent", "indigent",
  "indignant", "indolent", "indomitable", "ineffable", "ineluctable",
  "inexorable", "ingenuous", "inimical", "iniquity", "innate",
  "innocuous", "inscrutable", "insidious", "insipid", "insolent",
  "insouciant", "intractable", "intransigent", "intrepid", "intrinsic",
  "inundate", "inure", "invective", "inveterate", "invidious",
  "irascible", "irreverent", "itinerant",
  "jettison", "jingoism", "jovial", "jubilant", "judicious",
  "juxtapose",
  "kudos",
  "lachrymose", "laconic", "lament", "lampoon", "languid",
  "largesse", "lascivious", "lassitude", "laudable", "legerdemain",
  "levity", "libertine", "licentious", "limpid", "lithe",
  "litigious", "loquacious", "lucid", "lugubrious", "luminous",
  "lurid",
  "machination", "magnanimous", "maladroit", "malaise", "malfeasance",
  "malice", "malleable", "mandate", "manifest", "manifold",
  "martinet", "maudlin", "maverick", "mawkish", "maxim",
  "meander", "mediocre", "melancholy", "mellifluous", "mendacious",
  "mercenary", "mercurial", "meritorious", "metamorphosis", "meticulous",
  "milieu", "minuscule", "mirth", "misanthrope", "mitigate",
  "modicum", "mollify", "morose", "multifarious", "mundane",
  "munificent", "myriad",
  "nadir", "nascent", "nebulous", "nefarious", "neophyte",
  "nepotism", "nexus", "nihilism", "nonchalant", "nonpareil",
  "nostalgia", "notorious", "novel", "nuance", "nullify",
  "obdurate", "obfuscate", "oblique", "oblivion", "obsequious",
  "obstinate", "obstreperous", "obtuse", "occlude", "odious",
  "officious", "ominous", "omnipotent", "onerous", "opaque",
  "opprobrium", "opulent", "orate", "ornate", "orthodox",
  "oscillate", "ostentatious", "ostracize",
  "palatable", "palliate", "palpable", "panacea", "pandemic",
  "panegyric", "paradigm", "paradox", "paragon", "pariah",
  "parochial", "parsimonious", "partisan", "pastoral", "pathology",
  "pathos", "paucity", "pejorative", "pellucid", "penchant",
  "penitent", "penurious", "perennial", "perfidious", "perfunctory",
  "peripatetic", "pernicious", "perpetuate", "perspicacious", "pertinacious",
  "pervasive", "petulant", "philanthropy", "phlegmatic", "piety",
  "pillory", "pinnacle", "platitude", "plausible", "plethora",
  "poignant", "polemic", "ponderous", "portent", "pragmatic",
  "precedent", "precept", "precipitous", "preclude", "precocious",
  "predilection", "predominant", "preeminent", "prescient", "presumptuous",
  "prevail", "prevaricate", "pristine", "probity", "proclivity",
  "prodigal", "prodigious", "profligate", "profuse", "progenitor",
  "prognosticate", "prolific", "promulgate", "propensity", "propitious",
  "propriety", "prosaic", "proscribe", "protagonist", "protean",
  "provenance", "provincial", "provocative", "prudent", "pugnacious",
  "punctilious", "pundit", "pungent", "purport", "pusillanimous",
  "quagmire", "quandary", "quarantine", "querulous", "quiescent",
  "quintessential", "quixotic",
  "rancor", "rapacious", "rarefied", "raucous", "rebuke",
  "recalcitrant", "recant", "recondite", "redolent", "redoubtable",
  "refulgent", "refute", "relegate", "relinquish", "remonstrate",
  "renaissance", "renege", "replete", "reprehensible", "reprobate",
  "repudiate", "rescind", "resilient", "resolute", "resplendent",
  "restitution", "reticent", "retribution", "reverent", "rhetoric",
  "ribald", "risible", "rococo", "rudimentary", "ruminate",
  "rustic",
  "sacrilege", "sacrosanct", "sagacious", "salient", "salubrious",
  "salutary", "sanctimonious", "sanguine", "sardonic", "satiate",
  "scintillate", "scrupulous", "scrutinize", "sedentary", "seditious",
  "semblance", "sempiternal", "sententious", "serendipity", "servile",
  "simpatico", "sinecure", "skeptic", "sobriety", "solace",
  "solicitous", "soliloquy", "somnolent", "sonorous", "sophistry",
  "soporific", "sordid", "specious", "sporadic", "spurious",
  "squalid", "stagnant", "stalwart", "stoic", "strident",
  "stringent", "stymie", "subjugate", "sublime", "subterfuge",
  "succinct", "suffrage", "sundry", "superfluous", "supplant",
  "supplication", "surfeit", "surreptitious", "sycophant",
  "taciturn", "tangential", "tantalize", "temerity", "temperance",
  "tenacious", "tendentious", "terse", "thwart", "timorous",
  "tirade", "torpid", "tortuous", "tractable", "transgress",
  "transient", "trepidation", "trite", "truculent", "tumultuous",
  "turbulent", "turgid", "turpitude", "tutelage", "tyranny",
  "ubiquitous", "umbrage", "unctuous", "undermine", "unequivocal",
  "unfathomable", "ungainly", "unkempt", "unprecedented", "unscrupulous",
  "untenable", "upbraid", "usurp", "utilitarian",
  "vacillate", "vacuous", "vainglorious", "valiant", "vapid",
  "variegated", "vehement", "venal", "venerable", "venerate",
  "veracious", "verbose", "verdant", "vestige", "vexation",
  "vicarious", "vicissitude", "vigilant", "vilify", "vindicate",
  "vindictive", "virulent", "visceral", "vitriolic", "vituperate",
  "vivacious", "vociferous", "volatile", "volition", "voluminous",
  "voracious",
  "wanton", "whimsical", "wistful", "wrath",
  "xenophobia",
  "yearning",
  "zealous", "zenith", "zephyr"
];
